# Generated by Django 3.0.7 on 2020-06-08 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128, verbose_name='descrição')),
                ('due_date', models.DateTimeField(verbose_name='vencimento')),
                ('is_done', models.BooleanField(verbose_name='concluída')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='texto')),
                ('sent_date', models.DateTimeField(verbose_name='data de envio')),
                ('was_sent', models.BooleanField(verbose_name='enviado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'db_table': 'notification',
            },
        ),
    ]
