# Generated by Django 3.0.7 on 2020-06-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(default=None, max_length=128, verbose_name='título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(max_length=128, verbose_name='descrição'),
        ),
    ]
