# Generated by Django 3.0.7 on 2020-06-11 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasklist', '0003_auto_20200611_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
